### ISSUE TITLE
jo mangos 25/09

### ISSUE THREAD

**Issue by WillemVansteyvoort** [Jonanien/HelpdeskWillem#65]
- [x] Registeren min. characters (Daan) dit is in orde mijn vriendjes
- [x] tickets.php link naar ticket.php
- [x] ticket.php header fixee
- [x] Alle headers nakijken
- [x] logoke inzetten
- [x] wijzigww.php layout
- [x] profielpagina layout fixen
- [x] admin login: Gebruikertype -> 2
- [x] recentste versie online zetten (Jonathan)

**Comment by Jonanien** [comment]
-tickets.php link naar ticket.php
-ticket.php header fixee
-Alle headers nakijken
-logoke inzetten
-wijzigww.php layout
-profielpagina layout fixen
-admin login: Gebruikertype -> 2
-recentste versie online zetten (Jonathan)

**Comment by WillemVansteyvoort** [comment]
- [ ] tickets.php link naar ticket.php
- [ ] ticket.php header fixee
